apiVersion: v1
kind: Service
metadata:
  name: cipsvc
  labels:
    object: service
spec:
  type: ClusterIP
  selector:
    object: pod
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP